// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MochiApi.Models;

#nullable disable

namespace MochiApi.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MochiApi.Models.Budget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<int>("LimitAmount")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("SpentAmount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("WalletId");

                    b.HasIndex("Month", "Year");

                    b.ToTable("Budget", (string)null);
                });

            modelBuilder.Entity("MochiApi.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Group")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int?>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Group = 1,
                            Icon = "1",
                            Name = "Ăn uống",
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            Group = 1,
                            Icon = "2",
                            Name = "Di chuyển",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Group = 1,
                            Icon = "3",
                            Name = "Thuê nhà",
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            Group = 1,
                            Icon = "4",
                            Name = "Hóa đơn điện thoại",
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            Group = 1,
                            Icon = "5",
                            Name = "Hóa đơn internet",
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            Group = 1,
                            Icon = "6",
                            Name = "Hóa đơn tiện ích khác",
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            Group = 2,
                            Icon = "7",
                            Name = "Sửa & trang trí khác",
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            Group = 1,
                            Icon = "8",
                            Name = "Bảo dưỡng xe",
                            Type = 1
                        },
                        new
                        {
                            Id = 9,
                            Group = 2,
                            Icon = "1",
                            Name = "Khám sức khỏe",
                            Type = 1
                        },
                        new
                        {
                            Id = 10,
                            Group = 1,
                            Icon = "1",
                            Name = "Thể dục thể thao",
                            Type = 1
                        },
                        new
                        {
                            Id = 11,
                            Group = 0,
                            Icon = "1",
                            Name = "Lương",
                            Type = 0
                        },
                        new
                        {
                            Id = 12,
                            Group = 0,
                            Icon = "1",
                            Name = "Tiền ăn vặt",
                            Type = 0
                        },
                        new
                        {
                            Id = 13,
                            Group = 0,
                            Icon = "1",
                            Name = "Thu nhập khác",
                            Type = 0
                        },
                        new
                        {
                            Id = 14,
                            Group = 4,
                            Icon = "1",
                            Name = "Đầu tư",
                            Type = 1
                        },
                        new
                        {
                            Id = 15,
                            Group = 4,
                            Icon = "1",
                            Name = "Đi vay",
                            Type = 2
                        },
                        new
                        {
                            Id = 16,
                            Group = 4,
                            Icon = "1",
                            Name = "Cho vay",
                            Type = 4
                        },
                        new
                        {
                            Id = 17,
                            Group = 4,
                            Icon = "1",
                            Name = "Trả Nợ",
                            Type = 3
                        },
                        new
                        {
                            Id = 18,
                            Group = 4,
                            Icon = "1",
                            Name = "Thu Nợ",
                            Type = 5
                        },
                        new
                        {
                            Id = 19,
                            Group = 3,
                            Icon = "3",
                            Name = "Làm đẹp",
                            Type = 1
                        },
                        new
                        {
                            Id = 20,
                            Group = 3,
                            Icon = "4",
                            Name = "Quà tặng và quyên góp",
                            Type = 1
                        },
                        new
                        {
                            Id = 21,
                            Group = 3,
                            Icon = "4",
                            Name = "Dịch vụ trực tuyến",
                            Type = 1
                        },
                        new
                        {
                            Id = 22,
                            Group = 1,
                            Icon = "1",
                            Name = "Ăn uống",
                            Type = 1,
                            WalletId = 1
                        },
                        new
                        {
                            Id = 23,
                            Group = 1,
                            Icon = "2",
                            Name = "Di chuyển",
                            Type = 1,
                            WalletId = 1
                        },
                        new
                        {
                            Id = 24,
                            Group = 1,
                            Icon = "3",
                            Name = "Thuê nhà",
                            Type = 1,
                            WalletId = 1
                        },
                        new
                        {
                            Id = 25,
                            Group = 1,
                            Icon = "4",
                            Name = "Hóa đơn điện thoại",
                            Type = 1,
                            WalletId = 1
                        },
                        new
                        {
                            Id = 26,
                            Group = 1,
                            Icon = "5",
                            Name = "Hóa đơn internet",
                            Type = 1,
                            WalletId = 1
                        },
                        new
                        {
                            Id = 27,
                            Group = 1,
                            Icon = "6",
                            Name = "Hóa đơn tiện ích khác",
                            Type = 1,
                            WalletId = 1
                        },
                        new
                        {
                            Id = 28,
                            Group = 2,
                            Icon = "7",
                            Name = "Sửa & trang trí khác",
                            Type = 1,
                            WalletId = 1
                        },
                        new
                        {
                            Id = 29,
                            Group = 1,
                            Icon = "8",
                            Name = "Bảo dưỡng xe",
                            Type = 1,
                            WalletId = 1
                        },
                        new
                        {
                            Id = 30,
                            Group = 2,
                            Icon = "1",
                            Name = "Khám sức khỏe",
                            Type = 1,
                            WalletId = 1
                        },
                        new
                        {
                            Id = 31,
                            Group = 1,
                            Icon = "1",
                            Name = "Thể dục thể thao",
                            Type = 1,
                            WalletId = 1
                        },
                        new
                        {
                            Id = 32,
                            Group = 0,
                            Icon = "1",
                            Name = "Lương",
                            Type = 0,
                            WalletId = 1
                        },
                        new
                        {
                            Id = 33,
                            Group = 0,
                            Icon = "1",
                            Name = "Tiền ăn vặt",
                            Type = 0,
                            WalletId = 1
                        },
                        new
                        {
                            Id = 34,
                            Group = 0,
                            Icon = "1",
                            Name = "Thu nhập khác",
                            Type = 0,
                            WalletId = 1
                        },
                        new
                        {
                            Id = 35,
                            Group = 4,
                            Icon = "1",
                            Name = "Đầu tư",
                            Type = 1,
                            WalletId = 1
                        },
                        new
                        {
                            Id = 36,
                            Group = 4,
                            Icon = "1",
                            Name = "Đi vay",
                            Type = 2,
                            WalletId = 1
                        },
                        new
                        {
                            Id = 37,
                            Group = 4,
                            Icon = "1",
                            Name = "Cho vay",
                            Type = 4,
                            WalletId = 1
                        },
                        new
                        {
                            Id = 38,
                            Group = 4,
                            Icon = "1",
                            Name = "Trả Nợ",
                            Type = 3,
                            WalletId = 1
                        },
                        new
                        {
                            Id = 39,
                            Group = 4,
                            Icon = "1",
                            Name = "Thu Nợ",
                            Type = 5,
                            WalletId = 1
                        },
                        new
                        {
                            Id = 40,
                            Group = 3,
                            Icon = "3",
                            Name = "Làm đẹp",
                            Type = 1,
                            WalletId = 1
                        },
                        new
                        {
                            Id = 41,
                            Group = 3,
                            Icon = "4",
                            Name = "Quà tặng và quyên góp",
                            Type = 1,
                            WalletId = 1
                        },
                        new
                        {
                            Id = 42,
                            Group = 3,
                            Icon = "4",
                            Name = "Dịch vụ trực tuyến",
                            Type = 1,
                            WalletId = 1
                        },
                        new
                        {
                            Id = 43,
                            Group = 1,
                            Icon = "1",
                            Name = "Ăn uống",
                            Type = 1,
                            WalletId = 2
                        },
                        new
                        {
                            Id = 44,
                            Group = 1,
                            Icon = "2",
                            Name = "Di chuyển",
                            Type = 1,
                            WalletId = 2
                        },
                        new
                        {
                            Id = 45,
                            Group = 1,
                            Icon = "3",
                            Name = "Thuê nhà",
                            Type = 1,
                            WalletId = 2
                        },
                        new
                        {
                            Id = 46,
                            Group = 1,
                            Icon = "4",
                            Name = "Hóa đơn điện thoại",
                            Type = 1,
                            WalletId = 2
                        },
                        new
                        {
                            Id = 47,
                            Group = 1,
                            Icon = "5",
                            Name = "Hóa đơn internet",
                            Type = 1,
                            WalletId = 2
                        },
                        new
                        {
                            Id = 48,
                            Group = 1,
                            Icon = "6",
                            Name = "Hóa đơn tiện ích khác",
                            Type = 1,
                            WalletId = 2
                        },
                        new
                        {
                            Id = 49,
                            Group = 2,
                            Icon = "7",
                            Name = "Sửa & trang trí khác",
                            Type = 1,
                            WalletId = 2
                        },
                        new
                        {
                            Id = 50,
                            Group = 1,
                            Icon = "8",
                            Name = "Bảo dưỡng xe",
                            Type = 1,
                            WalletId = 2
                        },
                        new
                        {
                            Id = 51,
                            Group = 2,
                            Icon = "1",
                            Name = "Khám sức khỏe",
                            Type = 1,
                            WalletId = 2
                        },
                        new
                        {
                            Id = 52,
                            Group = 1,
                            Icon = "1",
                            Name = "Thể dục thể thao",
                            Type = 1,
                            WalletId = 2
                        },
                        new
                        {
                            Id = 53,
                            Group = 0,
                            Icon = "1",
                            Name = "Lương",
                            Type = 0,
                            WalletId = 2
                        },
                        new
                        {
                            Id = 54,
                            Group = 0,
                            Icon = "1",
                            Name = "Tiền ăn vặt",
                            Type = 0,
                            WalletId = 2
                        },
                        new
                        {
                            Id = 55,
                            Group = 0,
                            Icon = "1",
                            Name = "Thu nhập khác",
                            Type = 0,
                            WalletId = 2
                        },
                        new
                        {
                            Id = 56,
                            Group = 4,
                            Icon = "1",
                            Name = "Đầu tư",
                            Type = 1,
                            WalletId = 2
                        },
                        new
                        {
                            Id = 57,
                            Group = 4,
                            Icon = "1",
                            Name = "Đi vay",
                            Type = 2,
                            WalletId = 2
                        },
                        new
                        {
                            Id = 58,
                            Group = 4,
                            Icon = "1",
                            Name = "Cho vay",
                            Type = 4,
                            WalletId = 2
                        },
                        new
                        {
                            Id = 59,
                            Group = 4,
                            Icon = "1",
                            Name = "Trả Nợ",
                            Type = 3,
                            WalletId = 2
                        },
                        new
                        {
                            Id = 60,
                            Group = 4,
                            Icon = "1",
                            Name = "Thu Nợ",
                            Type = 5,
                            WalletId = 2
                        },
                        new
                        {
                            Id = 61,
                            Group = 3,
                            Icon = "3",
                            Name = "Làm đẹp",
                            Type = 1,
                            WalletId = 2
                        },
                        new
                        {
                            Id = 62,
                            Group = 3,
                            Icon = "4",
                            Name = "Quà tặng và quyên góp",
                            Type = 1,
                            WalletId = 2
                        },
                        new
                        {
                            Id = 63,
                            Group = 3,
                            Icon = "4",
                            Name = "Dịch vụ trực tuyến",
                            Type = 1,
                            WalletId = 2
                        },
                        new
                        {
                            Id = 64,
                            Group = 1,
                            Icon = "1",
                            Name = "Ăn uống",
                            Type = 1,
                            WalletId = 3
                        },
                        new
                        {
                            Id = 65,
                            Group = 1,
                            Icon = "2",
                            Name = "Di chuyển",
                            Type = 1,
                            WalletId = 3
                        },
                        new
                        {
                            Id = 66,
                            Group = 1,
                            Icon = "3",
                            Name = "Thuê nhà",
                            Type = 1,
                            WalletId = 3
                        },
                        new
                        {
                            Id = 67,
                            Group = 1,
                            Icon = "4",
                            Name = "Hóa đơn điện thoại",
                            Type = 1,
                            WalletId = 3
                        },
                        new
                        {
                            Id = 68,
                            Group = 1,
                            Icon = "5",
                            Name = "Hóa đơn internet",
                            Type = 1,
                            WalletId = 3
                        },
                        new
                        {
                            Id = 69,
                            Group = 1,
                            Icon = "6",
                            Name = "Hóa đơn tiện ích khác",
                            Type = 1,
                            WalletId = 3
                        },
                        new
                        {
                            Id = 70,
                            Group = 2,
                            Icon = "7",
                            Name = "Sửa & trang trí khác",
                            Type = 1,
                            WalletId = 3
                        },
                        new
                        {
                            Id = 71,
                            Group = 1,
                            Icon = "8",
                            Name = "Bảo dưỡng xe",
                            Type = 1,
                            WalletId = 3
                        },
                        new
                        {
                            Id = 72,
                            Group = 2,
                            Icon = "1",
                            Name = "Khám sức khỏe",
                            Type = 1,
                            WalletId = 3
                        },
                        new
                        {
                            Id = 73,
                            Group = 1,
                            Icon = "1",
                            Name = "Thể dục thể thao",
                            Type = 1,
                            WalletId = 3
                        },
                        new
                        {
                            Id = 74,
                            Group = 0,
                            Icon = "1",
                            Name = "Lương",
                            Type = 0,
                            WalletId = 3
                        },
                        new
                        {
                            Id = 75,
                            Group = 0,
                            Icon = "1",
                            Name = "Tiền ăn vặt",
                            Type = 0,
                            WalletId = 3
                        },
                        new
                        {
                            Id = 76,
                            Group = 0,
                            Icon = "1",
                            Name = "Thu nhập khác",
                            Type = 0,
                            WalletId = 3
                        },
                        new
                        {
                            Id = 77,
                            Group = 4,
                            Icon = "1",
                            Name = "Đầu tư",
                            Type = 1,
                            WalletId = 3
                        },
                        new
                        {
                            Id = 78,
                            Group = 4,
                            Icon = "1",
                            Name = "Đi vay",
                            Type = 2,
                            WalletId = 3
                        },
                        new
                        {
                            Id = 79,
                            Group = 4,
                            Icon = "1",
                            Name = "Cho vay",
                            Type = 4,
                            WalletId = 3
                        },
                        new
                        {
                            Id = 80,
                            Group = 4,
                            Icon = "1",
                            Name = "Trả Nợ",
                            Type = 3,
                            WalletId = 3
                        },
                        new
                        {
                            Id = 81,
                            Group = 4,
                            Icon = "1",
                            Name = "Thu Nợ",
                            Type = 5,
                            WalletId = 3
                        },
                        new
                        {
                            Id = 82,
                            Group = 3,
                            Icon = "3",
                            Name = "Làm đẹp",
                            Type = 1,
                            WalletId = 3
                        },
                        new
                        {
                            Id = 83,
                            Group = 3,
                            Icon = "4",
                            Name = "Quà tặng và quyên góp",
                            Type = 1,
                            WalletId = 3
                        },
                        new
                        {
                            Id = 84,
                            Group = 3,
                            Icon = "4",
                            Name = "Dịch vụ trực tuyến",
                            Type = 1,
                            WalletId = 3
                        },
                        new
                        {
                            Id = 85,
                            Group = 1,
                            Icon = "1",
                            Name = "Ăn uống",
                            Type = 1,
                            WalletId = 4
                        },
                        new
                        {
                            Id = 86,
                            Group = 1,
                            Icon = "2",
                            Name = "Di chuyển",
                            Type = 1,
                            WalletId = 4
                        },
                        new
                        {
                            Id = 87,
                            Group = 1,
                            Icon = "3",
                            Name = "Thuê nhà",
                            Type = 1,
                            WalletId = 4
                        },
                        new
                        {
                            Id = 88,
                            Group = 1,
                            Icon = "4",
                            Name = "Hóa đơn điện thoại",
                            Type = 1,
                            WalletId = 4
                        },
                        new
                        {
                            Id = 89,
                            Group = 1,
                            Icon = "5",
                            Name = "Hóa đơn internet",
                            Type = 1,
                            WalletId = 4
                        },
                        new
                        {
                            Id = 90,
                            Group = 1,
                            Icon = "6",
                            Name = "Hóa đơn tiện ích khác",
                            Type = 1,
                            WalletId = 4
                        },
                        new
                        {
                            Id = 91,
                            Group = 2,
                            Icon = "7",
                            Name = "Sửa & trang trí khác",
                            Type = 1,
                            WalletId = 4
                        },
                        new
                        {
                            Id = 92,
                            Group = 1,
                            Icon = "8",
                            Name = "Bảo dưỡng xe",
                            Type = 1,
                            WalletId = 4
                        },
                        new
                        {
                            Id = 93,
                            Group = 2,
                            Icon = "1",
                            Name = "Khám sức khỏe",
                            Type = 1,
                            WalletId = 4
                        },
                        new
                        {
                            Id = 94,
                            Group = 1,
                            Icon = "1",
                            Name = "Thể dục thể thao",
                            Type = 1,
                            WalletId = 4
                        },
                        new
                        {
                            Id = 95,
                            Group = 0,
                            Icon = "1",
                            Name = "Lương",
                            Type = 0,
                            WalletId = 4
                        },
                        new
                        {
                            Id = 96,
                            Group = 0,
                            Icon = "1",
                            Name = "Tiền ăn vặt",
                            Type = 0,
                            WalletId = 4
                        },
                        new
                        {
                            Id = 97,
                            Group = 0,
                            Icon = "1",
                            Name = "Thu nhập khác",
                            Type = 0,
                            WalletId = 4
                        },
                        new
                        {
                            Id = 98,
                            Group = 4,
                            Icon = "1",
                            Name = "Đầu tư",
                            Type = 1,
                            WalletId = 4
                        },
                        new
                        {
                            Id = 99,
                            Group = 4,
                            Icon = "1",
                            Name = "Đi vay",
                            Type = 2,
                            WalletId = 4
                        },
                        new
                        {
                            Id = 100,
                            Group = 4,
                            Icon = "1",
                            Name = "Cho vay",
                            Type = 4,
                            WalletId = 4
                        },
                        new
                        {
                            Id = 101,
                            Group = 4,
                            Icon = "1",
                            Name = "Trả Nợ",
                            Type = 3,
                            WalletId = 4
                        },
                        new
                        {
                            Id = 102,
                            Group = 4,
                            Icon = "1",
                            Name = "Thu Nợ",
                            Type = 5,
                            WalletId = 4
                        },
                        new
                        {
                            Id = 103,
                            Group = 3,
                            Icon = "3",
                            Name = "Làm đẹp",
                            Type = 1,
                            WalletId = 4
                        },
                        new
                        {
                            Id = 104,
                            Group = 3,
                            Icon = "4",
                            Name = "Quà tặng và quyên góp",
                            Type = 1,
                            WalletId = 4
                        },
                        new
                        {
                            Id = 105,
                            Group = 3,
                            Icon = "4",
                            Name = "Dịch vụ trực tuyến",
                            Type = 1,
                            WalletId = 4
                        });
                });

            modelBuilder.Entity("MochiApi.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("SpentAmount")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("WalletId");

                    b.ToTable("Event", (string)null);
                });

            modelBuilder.Entity("MochiApi.Models.Invitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SenderId");

                    b.HasIndex("UserId");

                    b.HasIndex("WalletId");

                    b.ToTable("Invitation", (string)null);
                });

            modelBuilder.Entity("MochiApi.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("BudgetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("InvitationId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSeen")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BudgetId");

                    b.HasIndex("InvitationId");

                    b.HasIndex("TransactionId");

                    b.HasIndex("UserId");

                    b.HasIndex("WalletId");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("MochiApi.Models.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Settings", (string)null);
                });

            modelBuilder.Entity("MochiApi.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AccumulatedAmount")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<int?>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ParticipantIds")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("RelevantTransactionId")
                        .HasColumnType("int");

                    b.Property<string>("UnknownParticipantsStr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("EventId");

                    b.HasIndex("RelevantTransactionId");

                    b.HasIndex("WalletId");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("MochiApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Avatar = "https://t4.ftcdn.net/jpg/02/23/50/73/360_F_223507349_F5RFU3kL6eMt5LijOaMbWLeHUTv165CB.jpg",
                            Email = "test@gmail.com",
                            Password = "123123123"
                        },
                        new
                        {
                            Id = 2,
                            Avatar = "https://t4.ftcdn.net/jpg/02/23/50/73/360_F_223507349_F5RFU3kL6eMt5LijOaMbWLeHUTv165CB.jpg",
                            Email = "test2@gmail.com",
                            Password = "123123123"
                        },
                        new
                        {
                            Id = 3,
                            Avatar = "https://t4.ftcdn.net/jpg/02/23/50/73/360_F_223507349_F5RFU3kL6eMt5LijOaMbWLeHUTv165CB.jpg",
                            Email = "test3@gmail.com",
                            Password = "123123123"
                        },
                        new
                        {
                            Id = 4,
                            Avatar = "https://t4.ftcdn.net/jpg/02/23/50/73/360_F_223507349_F5RFU3kL6eMt5LijOaMbWLeHUTv165CB.jpg",
                            Email = "test4@gmail.com",
                            Password = "123123123"
                        });
                });

            modelBuilder.Entity("MochiApi.Models.Wallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Balance")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Wallet", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 100000,
                            Icon = "",
                            IsDefault = true,
                            Name = "Ví",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Balance = 200000,
                            Icon = "",
                            IsDefault = true,
                            Name = "Ví",
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Balance = 300000,
                            Icon = "",
                            IsDefault = true,
                            Name = "Ví",
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            Balance = 400000,
                            Icon = "",
                            IsDefault = true,
                            Name = "Ví",
                            Type = 0
                        });
                });

            modelBuilder.Entity("MochiApi.Models.WalletMember", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("UserId", "WalletId");

                    b.HasIndex("WalletId");

                    b.ToTable("WalletMember", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            WalletId = 1,
                            JoinAt = new DateTime(2022, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 0,
                            Status = 0
                        },
                        new
                        {
                            UserId = 2,
                            WalletId = 2,
                            JoinAt = new DateTime(2022, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 0,
                            Status = 0
                        },
                        new
                        {
                            UserId = 3,
                            WalletId = 3,
                            JoinAt = new DateTime(2022, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 0,
                            Status = 0
                        },
                        new
                        {
                            UserId = 4,
                            WalletId = 4,
                            JoinAt = new DateTime(2022, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = 0,
                            Status = 0
                        });
                });

            modelBuilder.Entity("MochiApi.Models.Budget", b =>
                {
                    b.HasOne("MochiApi.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MochiApi.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MochiApi.Models.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Creator");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("MochiApi.Models.Category", b =>
                {
                    b.HasOne("MochiApi.Models.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("MochiApi.Models.Event", b =>
                {
                    b.HasOne("MochiApi.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MochiApi.Models.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId");

                    b.Navigation("Creator");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("MochiApi.Models.Invitation", b =>
                {
                    b.HasOne("MochiApi.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MochiApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MochiApi.Models.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sender");

                    b.Navigation("User");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("MochiApi.Models.Notification", b =>
                {
                    b.HasOne("MochiApi.Models.Budget", "Budget")
                        .WithMany()
                        .HasForeignKey("BudgetId");

                    b.HasOne("MochiApi.Models.Invitation", "Invitation")
                        .WithMany()
                        .HasForeignKey("InvitationId");

                    b.HasOne("MochiApi.Models.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId");

                    b.HasOne("MochiApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MochiApi.Models.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId");

                    b.Navigation("Budget");

                    b.Navigation("Invitation");

                    b.Navigation("Transaction");

                    b.Navigation("User");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("MochiApi.Models.Settings", b =>
                {
                    b.HasOne("MochiApi.Models.User", "User")
                        .WithOne("Settings")
                        .HasForeignKey("MochiApi.Models.Settings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MochiApi.Models.Transaction", b =>
                {
                    b.HasOne("MochiApi.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MochiApi.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MochiApi.Models.Event", "Event")
                        .WithMany("Transactions")
                        .HasForeignKey("EventId");

                    b.HasOne("MochiApi.Models.Transaction", "RelevantTransaction")
                        .WithMany()
                        .HasForeignKey("RelevantTransactionId");

                    b.HasOne("MochiApi.Models.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Creator");

                    b.Navigation("Event");

                    b.Navigation("RelevantTransaction");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("MochiApi.Models.WalletMember", b =>
                {
                    b.HasOne("MochiApi.Models.User", "User")
                        .WithMany("WalletMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MochiApi.Models.Wallet", "Wallet")
                        .WithMany("WalletMembers")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("MochiApi.Models.Event", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MochiApi.Models.User", b =>
                {
                    b.Navigation("Settings")
                        .IsRequired();

                    b.Navigation("WalletMembers");
                });

            modelBuilder.Entity("MochiApi.Models.Wallet", b =>
                {
                    b.Navigation("WalletMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
